/*//GEN-LINE:variables
 * Copyright (c) 2015 Sebastian Brudzinski
 * 
 * See the file LICENSE for copying permission.
 */
package latexstudio.editor;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import javax.swing.text.BadLocationException;
import latexstudio.editor.remote.DbxState;
import latexstudio.editor.settings.ApplicationSettings;
import latexstudio.editor.settings.SettingListener;
import latexstudio.editor.util.ApplicationUtils;
import org.apache.commons.io.IOUtils;
import org.fife.ui.autocomplete.AutoCompletion;
import org.fife.ui.autocomplete.BasicCompletion;
import org.fife.ui.autocomplete.CompletionProvider;
import org.fife.ui.autocomplete.DefaultCompletionProvider;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays the editor window.
 */
@ConvertAsProperties(
        dtd = "-//latexstudio.editor//Editor//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "EditorTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "latexstudio.editor.EditorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_EditorAction",
        preferredID = "EditorTopComponent"
)
@Messages({
    "CTL_EditorAction=Editor",
    "CTL_EditorTopComponent=Editor Window",
    "HINT_EditorTopComponent=This is a Editor window"
})
public final class EditorTopComponent extends TopComponent {

    private boolean dirty = false;
    private File currentFile;
    private DbxState dbxState;

    private AutoCompletion autoCompletion = null;
    public EditorTopComponent() {
        initComponents();
        setName(Bundle.CTL_EditorTopComponent());
        setDisplayName("welcome.tex");
        setToolTipText(Bundle.HINT_EditorTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
                
        ApplicationSettings.INSTANCE.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if(evt.getPropertyName().equals(ApplicationSettings.AUTOCOMPLETE_DELAY)&&autoCompletion!=null){
                    autoCompletion.setAutoActivationDelay((Integer)evt.getNewValue());
                }
            }
        });

    }

    //TODO 20160323 Make type checking work
    @SettingListener( setting = ApplicationSettings.Setting.AUTOCOMPLETE_ENABLED )
    public void setAutocompleteEnabled( String value ) {
        if(autoCompletion != null) {
            autoCompletion.setAutoActivationEnabled(Boolean.parseBoolean(value));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rSyntaxTextArea = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();

        rSyntaxTextArea.setColumns(20);
        rSyntaxTextArea.setRows(5);
        rSyntaxTextArea.setSyntaxEditingStyle(org.openide.util.NbBundle.getMessage(EditorTopComponent.class, "EditorTopComponent.rSyntaxTextArea.syntaxEditingStyle")); // NOI18N
        rSyntaxTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rSyntaxTextAreaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rSyntaxTextAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(rSyntaxTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void rSyntaxTextAreaKeyReleased(java.awt.event.KeyEvent evt) {                                            
        dirty = true;
    }                                           

    private void rSyntaxTextAreaKeyTyped(java.awt.event.KeyEvent evt) {                                         
        if (currentFile == null || evt.isControlDown()) return;
        setDisplayName(currentFile.getName() + '*');
    }                                        

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea rSyntaxTextArea;
    // End of variables declaration                   

    @Override
    public void componentOpened() {
        ApplicationUtils.deleteTempFiles();
        CompletionProvider provider = createCompletionProvider();
        autoCompletion = new AutoCompletion(provider);
        autoCompletion.setAutoActivationDelay(ApplicationSettings.INSTANCE.getAutoCompleteDelay());
        autoCompletion.setAutoActivationEnabled(true);
        autoCompletion.setAutoCompleteEnabled(true);
        autoCompletion.install(rSyntaxTextArea);

        ApplicationSettings.INSTANCE.registerSettingListeners(this);
        
        InputStream is = null;
        try {
            is = getClass().getResource("/latexstudio/editor/resources/welcome.tex").openStream();
            String welcomeMessage = IOUtils.toString(is);
            rSyntaxTextArea.setText(welcomeMessage);
            setDirty(true);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        } finally {
            IOUtils.closeQuietly(is);
        }
    }

    @Override
    public void componentClosed() {
    }

    public String getEditorContent() {
        return rSyntaxTextArea.getText();
    }

    public void setEditorContent(String text) {
        rSyntaxTextArea.setText(text);
        dirty = true;
    }

    public boolean isDirty() {
        return dirty;
    }

    public void setDirty(boolean dirty) {
        this.dirty = dirty;
    }

    public void undoAction() {
        rSyntaxTextArea.undoLastAction();
    }

    public void redoAction() {
        rSyntaxTextArea.redoLastAction();
    }

    public File getCurrentFile() {
        return currentFile;
    }

    public void setCurrentFile(File currentFile) {
        this.currentFile = currentFile;
        setDisplayName(currentFile.getName());
    }

    public DbxState getDbxState() {
        return dbxState;
    }

    public void setDbxState(DbxState dbxState) {
        this.dbxState = dbxState;
    }

    private String findStartSymbol() {
        String highlightedTextArea2 = null;
        boolean toggle = true;
        int carretCoordinates;
        while (toggle) {
            carretCoordinates = rSyntaxTextArea.getSelectionStart();
            if (rSyntaxTextArea.getSelectedText().startsWith("\n") || rSyntaxTextArea.getSelectionStart() == 0) {
                toggle = false;
                if (rSyntaxTextArea.getSelectionStart() != 0) {
                    rSyntaxTextArea.select(carretCoordinates + 1, rSyntaxTextArea.getSelectionEnd());
                    highlightedTextArea2 = rSyntaxTextArea.getSelectedText();
                    return highlightedTextArea2;
                } else {
                    rSyntaxTextArea.select(carretCoordinates, rSyntaxTextArea.getSelectionEnd());
                    highlightedTextArea2 = rSyntaxTextArea.getSelectedText();
                    return highlightedTextArea2;
                }

            } else {
                carretCoordinates--;
                rSyntaxTextArea.select(carretCoordinates, rSyntaxTextArea.getSelectionEnd());

            }

        }
        highlightedTextArea2 = rSyntaxTextArea.getSelectedText();
        return highlightedTextArea2;
    }

    public void commentOutText() {
        String highlightedTextArea = rSyntaxTextArea.getSelectedText();
        if (highlightedTextArea != null) {
            highlightedTextArea = findStartSymbol();
            if (highlightedTextArea.startsWith("%")) {
                rSyntaxTextArea.replaceSelection(highlightedTextArea.replace("%", ""));

            } else {
                String[] array = highlightedTextArea.split("\n");
                String tempStr = "";
                for (int i = 0; i < array.length; i++) {
                    if (i != array.length - 1) {
                        array[i] = "%" + array[i] + "\n";
                        tempStr = tempStr + array[i];
                    } else {
                        array[i] = "%" + array[i];
                        tempStr = tempStr + array[i];
                    }

                }
                rSyntaxTextArea.replaceSelection(tempStr);
            }
        } else {
            try {
                int currentOffsetFromLineStart = rSyntaxTextArea.getCaretOffsetFromLineStart();
                int currentCaretPosition = 0;
                int lineStartPosition = 0;
                currentCaretPosition = rSyntaxTextArea.getCaretPosition();
                lineStartPosition = currentCaretPosition - currentOffsetFromLineStart;
                int lineLength = rSyntaxTextArea.getLineEndOffsetOfCurrentLine();
                String firstChar = rSyntaxTextArea.getText(lineStartPosition, lineLength - lineStartPosition);
                if (firstChar.startsWith("%")) {
                    rSyntaxTextArea.replaceRange("", lineStartPosition, lineStartPosition + 1);
                } else {
                    rSyntaxTextArea.replaceRange("%", lineStartPosition, lineStartPosition);
                }
            } catch (BadLocationException ex) {
                Exceptions.printStackTrace(ex);
            }
        }

    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private CompletionProvider createCompletionProvider() {
        DefaultCompletionProvider provider = new DefaultCompletionProvider();
        provider.setAutoActivationRules(true, "");

        URL[] urls = new URL[3];
        urls[0] = getClass().getResource("/latexstudio/editor/resources/tex.cwl");
        urls[1] = getClass().getResource("/latexstudio/editor/resources/latex-document.cwl");
        urls[2] = getClass().getResource("/latexstudio/editor/resources/latex-mathsymbols.cwl");

        for (URL url : urls) {
            InputStream is = null;
            try {
                is = url.openStream();
                BufferedReader br = new BufferedReader(new InputStreamReader(is));
                String line;
                while ((line = br.readLine()) != null) {
                    if (!line.startsWith("#")) {
                        provider.addCompletion(new BasicCompletion(provider, line.substring(1)));
                    }
                }
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            } finally {
                IOUtils.closeQuietly(is);
            }
        }

        return provider;
    }
}

